### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by kfuglsang** [sensu-plugins/sensu-plugins-influxdb#15]
Could you release the latest version such that it will be installed using `sensu-install`?
The tags support in metrics-influxdb.rb is very useful.

**Comment by envintus** [comment]
👍  - @portertech, @mattyjones, @analytically

**Comment by mattyjones** [comment]
@kfuglsang 
[0.0.7](https://github.com/sensu-plugins/sensu-plugins-influxdb/releases/tag/0.0.7)
