### ISSUE TITLE
metrics-influxdb.rb fails to write points if database already exists

### ISSUE THREAD

**Issue by leelasharma** [sensu-plugins/sensu-plugins-influxdb#22]
Noticed that the  latest version fails to write points to influxdb, the recently added create_database call fails if database already exists.
Ideally it should be checked if database exists before attempting to create. Also its an additional and expensive operation to try to create a database each time(needs to be done once)  when trying to write points(which happens very often)

**Comment by xgin** [comment]
Encountered the same problem.
When I was preparing the patch with the query: "CREATE DATABASE IF NOT EXISTS ...", I have found out the "IF NOT EXISTS" clause is deprecated:
https://docs.influxdata.com/influxdb/v0.13/query_language/database_management/#create-a-database-with-create-database

>  If you attempt to create a database that already exists, InfluxDB does not return an error.

I have upgraded to the latest version of influxdb and the problem has gone away.

**Comment by eheydrick** [comment]
is this still an issue?
