### ISSUE TITLE
Please update the readme

### ISSUE THREAD

**Issue by JasonIamAUnixAdmin** [sensu-plugins/sensu-plugins-influxdb#23]
The readme does not covey the setup of the plugin well. Document should be something like:
Add the following to your `/etc/sensu/conf.d/influx.conf` and then the sample in the current readme.md 

then add the following to your `/etc/sensu/conf.d/handlers.conf`:

`````` json
     "influx-tcp": {
       "type": "pipe",
       "command": "/opt/sensu/embedded/bin/metrics-influxdb.rb"
     },```
``````

**Comment by eheydrick** [comment]
Want to put together a PR with README updates?

**Comment by JasonIamAUnixAdmin** [comment]
PR has been created

**Comment by eheydrick** [comment]
Thanks!
